# Generated by Django 5.2.3 on 2025-07-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_categoria_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='data_emprestimo',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='nome_emprestado',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='tempo_duracao',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.livros'),
            preserve_default=False,
        ),
    ]
