# Generated by Django 5.2.3 on 2025-07-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_remove_emprestimo_categoria_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='nome_emprestado',
            new_name='locatario_desconhecido',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='locatario_registrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
